### ISSUE TITLE
Change directory returning 1 unhandled.

### ISSUE THREAD

**Issue by RyanFleck** [RyanFleck/SuperPull#2]
If a repository has been removed, `cd` returning `1` is not handled.

```sh
rflec028@gnubox:~$ superpull
SuperPull repositories.

{ Error: Command failed: cd /home/rflec028/Rails-App-One/ && pwd && git fetch --all && git pull
/bin/sh: 1: cd: can't cd to /home/rflec028/Rails-App-One/

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:595:12)
  killed: false,
  code: 2,
  signal: null,
  cmd:
   'cd /home/rflec028/Rails-App-One/ && pwd && git fetch --all && git pull' }
/bin/sh: 1: cd: can't cd to /home/rflec028/Rails-App-One/
```

**Comment by RyanFleck** [comment]
Closing - SuperPull now checks if dir exists before attempting sync.
